### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by trondkr** [ecohealthalliance/parse-server-amazon-ses-email-adapter#1]
I keep getting an error trying to deploy my index.js after adding support for email verification using your code. I am not an experienced javascript programmer so I may be doing something erroneous. Do you see what may cause  me to get 

```
/var/app/current/index.js:24
  emailAdapter: {
  ^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

Thanks! Cheers, Trond

My index.js:

```
// Example express application adding the parse-server module to expose Parse
// compatible API routes.

var express = require('express');
var ParseServer = require('parse-server').ParseServer;
var path = require('path');

var databaseUri = process.env.DATABASE_URI || process.env.MONGODB_URI;

if (!databaseUri) {
  console.log('DATABASE_URI not specified, falling back to localhost.');
}

var api = new ParseServer({
  databaseURI: databaseUri || 'mongodb://localhost:27017/dev',
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  appId: process.env.APP_ID || 'myAppId',
  masterKey: process.env.MASTER_KEY || '', //Add your master key here. Keep it secret!
  fileKey: process.env.FILE_KEY || '', // Add the file key to provide access to files already hosted on Parse
  serverURL: process.env.SERVER_URL || 'http://localhost:1337/parse',  // Don't forget to change to https if needed
  liveQuery: {
    classNames: ["Posts", "Comments"] // List of classes to support for query subscriptions
  },
  emailAdapter: {
      module: "parse-server-amazon-ses-email-adapter",
      options: {
         fromAddress: "domain <noreply@domain.com>",
         accessKeyId: "keyId",
         secretAccessKey: "AccessKey",
         region: "us-east-1",
         // The template section
         templates: {
           passwordResetEmail: {
             subject: 'Reset your password',
             pathPlainText: resolve(__dirname, '/public/templates/password_reset_email.txt'),
             pathHtml: resolve(__dirname, '/public/templates/password_reset_email.html'),
             callback: (user) => {
                 return {
                   firstName: user.get('firstName')
                 }
               }
              // Now you can use {{firstName}} in your templates
           },
           verificationEmail: {
             subject: 'Confirm your account',
             pathPlainText: resolve(__dirname, '/public/templates/verification_email.txt'),
             pathHtml: resolve(__dirname, '/public/templates/verification_email.html'),
             callback: (user) => {
                 return {
                   firstName: user.get('firstName')
                 }
               }
               // Now you can use {{firstName}} in your templates
           },
           customEmailAlert: {
             subject: 'Urgent notification!',
             pathPlainText: resolve(__dirname, '/public/templates/custom_alert.txt'),
             pathHtml: resolve(__dirname, '/public/templates/custom_alert.html'),
           }
         }
       }
    }
});
// Client-keys like the javascript key or the .NET key are not necessary with parse-server
// If you wish you require them, you can set them as options in the initialization above:
// javascriptKey, restAPIKey, dotNetKey, clientKey

var app = express();

// Serve static assets from the /public folder
app.use('/public', express.static(path.join(__dirname, '/public')));

// Serve the Parse API on the /parse URL prefix
var mountPath = process.env.PARSE_MOUNT || '/parse';
app.use(mountPath, api);

// Parse Server plays nicely with the rest of your web routes
app.get('/', function(req, res) {
  res.status(200).send('Make sure to star the parse-server repo on GitHub!');
});

// There will be a test page available on the /test path of your server url
// Remove this before launching your app
app.get('/test', function(req, res) {
  res.sendFile(path.join(__dirname, '/public/test.html'));
});

var port = process.env.PORT || 1337;
var httpServer = require('http').createServer(app);
httpServer.listen(port, function() {
    console.log('parse-server-example running on port ' + port + '.');
});

// This will enable the Live Query real-time server
ParseServer.createLiveQueryServer(httpServer);
```

**Comment by dan-nyanko** [comment]
I think the issue you're having is due to lack of ES6 support in your environment (in particular, the fat arrow functions used in the callbacks). Try replacing with `function(user){ return ... }`

**Comment by dan-nyanko** [comment]
@trondkr Also, if you're interested in setting up parse-sever using [babel](https://babeljs.io/) transpiler for ES6 feature, check out our [gq-parse-server](https://github.com/ecohealthalliance/gq-parse-server) repository.

**Comment by trondkr** [comment]
Thanks for your reply. I really have not enough experience in Javascript, but to me it seems that the server (AWS Elastic Beanstalk running nginx) is unable to understand what  `},
  emailAdapter: {` means or whether my syntax is wrong? Are you sure its the callback functions and not some requirement that I need to add? If it is the callback function would you mind helping me with the syntax of how to rewrite the current code? i appreciate your help! Cheers, Trond

**Comment by trondkr** [comment]
I figured this out. Turns out it was a missing comma. Thanks. T
