### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Awatatah** [ecohealthalliance/parse-server-amazon-ses-email-adapter#5]
I cannot get this to work. I receive the below error. I even tried added 'regenerator-runtime'as a dependency in my app
"regenerator-runtime": "^0.12.1"

```error: Error generating response. [ReferenceError: regeneratorRuntime is not defined] 
error: Uncaught internal server error. [ReferenceError: regeneratorRuntime is not defined] ReferenceError: regeneratorRuntime is not defined
    at AmazonSESAdapter._sendMail (/parse/node_modules/parse-server-amazon-ses-email-adapter/lib/AmazonSESAdapter.js:161:32)
    at AmazonSESAdapter.send (/parse/node_modules/parse-server-amazon-ses-email-adapter/lib/AmazonSESAdapter.js:306:19)
    at /parse/cloud/main.js:94:20
    at _ret.v (/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:203:15)
    at /parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:171:16
    at handleCloudFunction (/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:206:10)
    at /parse/node_modules/parse-server/lib/PromiseRouter.js:253:9
    at /parse/node_modules/parse-server/lib/PromiseRouter.js:289:9
    at Layer.handle [as handle_request] (/parse/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/parse/node_modules/parse-server/node_modules/express/lib/router/route.js:131:13)
ReferenceError: regeneratorRuntime is not defined
    at AmazonSESAdapter._sendMail (/parse/node_modules/parse-server-amazon-ses-email-adapter/lib/AmazonSESAdapter.js:161:32)
    at AmazonSESAdapter.send (/parse/node_modules/parse-server-amazon-ses-email-adapter/lib/AmazonSESAdapter.js:306:19)
    at /parse/cloud/main.js:94:20
    at _ret.v (/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:203:15)
    at /parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:171:16
    at handleCloudFunction (/parse/node_modules/parse-server/lib/Routers/FunctionsRouter.js:206:10)
    at /parse/node_modules/parse-server/lib/PromiseRouter.js:253:9
    at /parse/node_modules/parse-server/lib/PromiseRouter.js:289:9
    at Layer.handle [as handle_request] (/parse/node_modules/parse-server/node_modules/express/lib/router/layer.js:95:5)
    at next (/parse/node_modules/parse-server/node_modules/express/lib/router/route.js:131:13)```

**Comment by Awatatah** [comment]
I resolved by installing `@babel/polyfill` and adding `require("@babel/polyfill");` to my app
